name: 'Sysdig Secure Inline Scan'
description: 'Perform image analysis on locally built container image and post the result of the analysis to Sysdig Secure.'
inputs:
  cli-scanner-url:
    description: URL to sysdig-cli-scanner binary download
    default: https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/1.8.1/linux/amd64/sysdig-cli-scanner
    required: false
  cli-scanner-version:
    description: Custom sysdig-cli-scanner version to download
    default: "1.8.1"
    required: false
  registry-user:
    description: Registry username.
    required: false
  registry-password:
    description: Registry password.
    required: false
  stop-on-failed-policy-eval:
    description: Fail the job if the Policy Evaluation is Failed.
    default: "false"
    required: false
  stop-on-processing-error:
    description: Fail the job if the Scanner terminates execution with errors.
    default: "false"
    required: false
  standalone:
    description: Enable standalone mode. Do not depend on Sysdig backend for execution, avoiding the need of specifying 'sysdig-secure-token' and 'sysdig-secure-url'.
    default: "false"
    required: false
  db-path:
    description: Specify directory for database to use while scanning.
    required: false
  skip-upload:
    description: Skip uploading results to Sysdig Secure.
    default: "false"
    required: false
  skip-summary:
    description: Skip generating Summary.
    default: "false"
    required: false 
  use-policies:
    description: Specify Sysdig Secure VM Policies to evaluate the image.
    required: false
  override-pullstring:
    description: Custom PullString to give the image when scanning and uploading. 
    required: false
  image-tag:
    description: Tag of the image to analyse.
    required: true
  sysdig-secure-token:
    description: API token for Sysdig Scanning auth. (Required if not in Standalone mode.)
    required: false
  sysdig-secure-url:
    description: 'Sysdig Secure URL (ex: "https://secure-sysdig.com").'
    required: false
    default: https://secure.sysdig.com
  sysdig-skip-tls:
    description: Skip TLS verification when calling secure endpoints.
    required: false
  extra-parameters:
    description: Additional parameters added to the secure-inline-scan container execution.
    required: false
outputs:
  scanReport:
    description: Path to a JSON file containing the report results, failed evaluation gates, and found vulnerabilities.
  sarifReport:
    description: |
      Path to a SARIF report, that can be uploaded using the codeql-action/upload-sarif action. See the README for more information.

branding:
  icon: 'shield'
  color: 'orange'
runs:
  using: 'node20'
  main: 'dist/index.js'
